### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by sirreal**
Shall we get on more current dependency versions for a new release (#10)?

### CODE REVIEW

**Comment by sirreal** [comment]
Needs some work…

**Comment by sirreal** [comment]
Updated to latest `jdsom@9` before major breaking API changes.

Support oldest node versions that aren't end-of-life (6, LTS(8) and stable (10))

**Comment by ockham** [comment]
...or should we maybe get rid of this thing entirely (by migrating i18n-calypso to Jest)? :thinking: Cf. https://github.com/Automattic/wp-calypso/pull/19150

**Comment by ockham** [comment]
Maybe it's only needed for testing i18n-calypso's mixin, which we should get rid of anyway...

**Comment by ockham** [comment]
I'll look into that ^

**Comment by ockham** [comment]
https://github.com/Automattic/i18n-calypso/pull/58

So let's maybe think about deprecating this repo?

**Comment by sirreal** [comment]
That's a great idea, but I checked and it's used in a few Automattic projects: https://github.com/search?q=org%3AAutomattic+react-test-env&type=Code

**Comment by ockham** [comment]
https://www.youtube.com/watch?v=oOS00ttAblQ

(One at a time.)

**Comment by sirreal** [comment]
477-gh-homemade-linguine

**Comment by sirreal** [comment]
47-gh-mc-calypso

**Comment by sirreal** [comment]
Prefer archive/deprecate: #12

**Pull request closed without merging**
